/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.view;

import calculator.domain.Calculator;
import calculator.domain.operations.Addition;
import calculator.domain.operations.Division;
import calculator.domain.operations.Multiplication;
import calculator.domain.operations.Subtraction;
import javax.swing.JOptionPane;

/**
 *
 * @author emutis
 */
public class ViewApplication extends javax.swing.JFrame {

  private String firstNumber = "";
  private String operator = "";

  /**
   * Creates new form VistaAplicativo
   */
  public ViewApplication() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * Displays a message to the user.
   * @param message The message to display.
   */
  public void displayMessage(String message) {
    JOptionPane.showMessageDialog(this, message);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton4 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    casilla = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();

    jButton4.setText("jButton1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(51, 204, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    casilla.setBackground(new java.awt.Color(255, 255, 255));
    casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    casilla.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(0, 102, 255)
      )
    );
    casilla.setOpaque(true);

    jButton1.setText("C");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton2.setText("/");
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    jButton3.setText("*");
    jButton3.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton3ActionPerformed(evt);
        }
      }
    );

    jButton5.setText("-");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    jButton6.setText("7");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    jButton7.setText("8");
    jButton7.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton7ActionPerformed(evt);
        }
      }
    );

    jButton8.setText("9");
    jButton8.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton8ActionPerformed(evt);
        }
      }
    );

    jButton9.setText("+");
    jButton9.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton9ActionPerformed(evt);
        }
      }
    );

    jButton10.setText("4");
    jButton10.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton10ActionPerformed(evt);
        }
      }
    );

    jButton11.setText("5");
    jButton11.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton11ActionPerformed(evt);
        }
      }
    );

    jButton12.setText("6");
    jButton12.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton12ActionPerformed(evt);
        }
      }
    );

    jButton14.setText("1");
    jButton14.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton14ActionPerformed(evt);
        }
      }
    );

    jButton15.setText("2");
    jButton15.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton15ActionPerformed(evt);
        }
      }
    );

    jButton16.setText("3");
    jButton16.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton16ActionPerformed(evt);
        }
      }
    );

    jButton18.setText("0");
    jButton18.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton18ActionPerformed(evt);
        }
      }
    );

    jButton20.setText(".");
    jButton20.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton20ActionPerformed(evt);
        }
      }
    );

    jButton21.setText("=");
    jButton21.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton21ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addComponent(
                      jButton1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jButton2,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jButton3,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jButton5,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addComponent(
                  casilla,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(
                              jButton6,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton7,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton8,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(
                              jButton10,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton11,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton12,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jButton9,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(
                              jButton14,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton15,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton16,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(
                              jButton18,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              90,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jButton20,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              42,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jButton21,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      42,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              casilla,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              32,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jButton1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  42,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jButton2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  42,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jButton3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  42,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jButton5,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  42,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jButton6,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton7,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton8,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jButton10,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton11,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton12,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
                .addComponent(
                  jButton9,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jButton14,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton15,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton16,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jButton18,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jButton20,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          42,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
                .addComponent(
                  jButton21,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(0, 10, Short.MAX_VALUE)
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton18ActionPerformed
    this.casilla.setText(this.casilla.getText() + "0");
  } //GEN-LAST:event_jButton18ActionPerformed

  private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton14ActionPerformed
    this.casilla.setText(this.casilla.getText() + "1");
  } //GEN-LAST:event_jButton14ActionPerformed

  private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton15ActionPerformed
    this.casilla.setText(this.casilla.getText() + "2");
  } //GEN-LAST:event_jButton15ActionPerformed

  private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton16ActionPerformed
    this.casilla.setText(this.casilla.getText() + "3");
  } //GEN-LAST:event_jButton16ActionPerformed

  private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton10ActionPerformed
    this.casilla.setText(this.casilla.getText() + "4");
  } //GEN-LAST:event_jButton10ActionPerformed

  private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton11ActionPerformed
    this.casilla.setText(this.casilla.getText() + "5");
  } //GEN-LAST:event_jButton11ActionPerformed

  private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton12ActionPerformed
    this.casilla.setText(this.casilla.getText() + "6");
  } //GEN-LAST:event_jButton12ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    this.casilla.setText(this.casilla.getText() + "7");
  } //GEN-LAST:event_jButton6ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton7ActionPerformed
    this.casilla.setText(this.casilla.getText() + "8");
  } //GEN-LAST:event_jButton7ActionPerformed

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton8ActionPerformed
    this.casilla.setText(this.casilla.getText() + "9");
  } //GEN-LAST:event_jButton8ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    this.casilla.setText("");
    this.firstNumber = "";
    this.operator = "";
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton21ActionPerformed
    try {
      double result;
      double firstNumber = Double.parseDouble(this.firstNumber);
      double secondNumber = Double.parseDouble(casilla.getText());

      Calculator calculator = new Calculator();

      switch (this.operator) {
        case "+" -> calculator.setOperation(new Addition());
        case "-" -> calculator.setOperation(new Subtraction());
        case "*" -> calculator.setOperation(new Multiplication());
        case "/" -> calculator.setOperation(new Division());
      }

      if (this.operator.equals("/") && secondNumber == 0) {
        if (firstNumber == 0) {
          casilla.setText("No se puede dividir entre cero");
        } else {
          casilla.setText("Error: División por cero");
        }
      } else {
        result = calculator.calculate(firstNumber, secondNumber);
        casilla.setText(String.valueOf(result));
      }
    } catch (NumberFormatException | ArithmeticException e) {
      casilla.setText("Error");
    }
  } //GEN-LAST:event_jButton21ActionPerformed

  private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton9ActionPerformed
    firstNumber = casilla.getText();
    operator = "+";
    casilla.setText("");
  } //GEN-LAST:event_jButton9ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    handleNegativeSignButton();
  } //GEN-LAST:event_jButton5ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton3ActionPerformed
    firstNumber = casilla.getText();
    operator = "*";
    casilla.setText("");
  } //GEN-LAST:event_jButton3ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
    firstNumber = casilla.getText();
    operator = "/";
    casilla.setText("");
  } //GEN-LAST:event_jButton2ActionPerformed

  private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton20ActionPerformed
    if (!casilla.getText().contains(".")) {
      casilla.setText(casilla.getText() + ".");
    }
  } //GEN-LAST:event_jButton20ActionPerformed

  private void handleNegativeSignButton() {
    String currentText = casilla.getText();

    if (currentText.isEmpty()) {
      casilla.setText("-");
    } else {
      if (currentText.startsWith("-")) {
        casilla.setText(currentText.substring(1));
      } else {
        casilla.setText("-" + currentText);
      }
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(ViewApplication.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(ViewApplication.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(ViewApplication.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(ViewApplication.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new ViewApplication().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel casilla;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
